/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Games/albumly`; params?: Router.UnknownInputParams; } | { pathname: `/Games/artistly`; params?: Router.UnknownInputParams; } | { pathname: `/Games/songly`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/gamePage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/profilePage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/searchPage`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Games/albumly`; params?: Router.UnknownOutputParams; } | { pathname: `/Games/artistly`; params?: Router.UnknownOutputParams; } | { pathname: `/Games/songly`; params?: Router.UnknownOutputParams; } | { pathname: `/Nav Pages/gamePage`; params?: Router.UnknownOutputParams; } | { pathname: `/Nav Pages/postPage`; params?: Router.UnknownOutputParams; } | { pathname: `/Nav Pages/profilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/Nav Pages/searchPage`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Games/albumly${`?${string}` | `#${string}` | ''}` | `/Games/artistly${`?${string}` | `#${string}` | ''}` | `/Games/songly${`?${string}` | `#${string}` | ''}` | `/Nav Pages/gamePage${`?${string}` | `#${string}` | ''}` | `/Nav Pages/postPage${`?${string}` | `#${string}` | ''}` | `/Nav Pages/profilePage${`?${string}` | `#${string}` | ''}` | `/Nav Pages/searchPage${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Games/albumly`; params?: Router.UnknownInputParams; } | { pathname: `/Games/artistly`; params?: Router.UnknownInputParams; } | { pathname: `/Games/songly`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/gamePage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/profilePage`; params?: Router.UnknownInputParams; } | { pathname: `/Nav Pages/searchPage`; params?: Router.UnknownInputParams; };
    }
  }
}
