/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/albumly`; params?: Router.UnknownInputParams; } | { pathname: `/artistly`; params?: Router.UnknownInputParams; } | { pathname: `/gamePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/profilePage`; params?: Router.UnknownInputParams; } | { pathname: `/searchPage`; params?: Router.UnknownInputParams; } | { pathname: `/songly`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/albumly`; params?: Router.UnknownOutputParams; } | { pathname: `/artistly`; params?: Router.UnknownOutputParams; } | { pathname: `/gamePage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/postPage`; params?: Router.UnknownOutputParams; } | { pathname: `/profilePage`; params?: Router.UnknownOutputParams; } | { pathname: `/searchPage`; params?: Router.UnknownOutputParams; } | { pathname: `/songly`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/albumly${`?${string}` | `#${string}` | ''}` | `/artistly${`?${string}` | `#${string}` | ''}` | `/gamePage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/postPage${`?${string}` | `#${string}` | ''}` | `/profilePage${`?${string}` | `#${string}` | ''}` | `/searchPage${`?${string}` | `#${string}` | ''}` | `/songly${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/albumly`; params?: Router.UnknownInputParams; } | { pathname: `/artistly`; params?: Router.UnknownInputParams; } | { pathname: `/gamePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/postPage`; params?: Router.UnknownInputParams; } | { pathname: `/profilePage`; params?: Router.UnknownInputParams; } | { pathname: `/searchPage`; params?: Router.UnknownInputParams; } | { pathname: `/songly`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
